/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=CloudflareEnv src/cloudflare-env.d.ts` (hash: 02e752476e12f7de4809192102224fc9)
interface __BaseEnv_CloudflareEnv {
	DB: D1Database;
	NOWPLAYING_DO: DurableObjectNamespace<import("../worker/index").NowPlayingDO>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("../worker/index");
		durableNamespaces: "NowPlayingDO";
	}
	interface Env extends __BaseEnv_CloudflareEnv {}
}
interface CloudflareEnv extends __BaseEnv_CloudflareEnv {}
